### ISSUE TITLE
ln command is not being run

### ISSUE THREAD

**Issue by zhisme** [runar/capistrano-linked-files#6]
Is this gem intended only to upload linked files?
because I had manually add the following command to start my app going.

`ln -nfs /var/www/app_name/shared/.rbenv-vars .rbenv-vars`
So the link now provided and 
`rbenv vars`
returns not nil result.
may be the gem is broken?

I thought the main reason of the gem is to upload linked files, and then link them to current directory.

Best regards
Eugene.

**Comment by zhisme** [comment]
`deploy.rb`
```
...
desc 'link dotenv files'
  task :final_link_files do
    on roles(:app) do
      within "#{current_path}" do
        execute "ln -nfs /var/www/#{fetch(:application)}/shared/.rbenv-vars .rbenv-vars"
      end
    end
  end

...
after  :finishing,    :final_link_files
...
```

so my fix to this issue look like this. Hope it helps for someone else.

**Comment by runar** [comment]
Thank you for your report! However, Capistrano, not this gem, is responsible for symlinking the shared files and directories into each release. If some or all of your files are not being symlinked, the issue is most likely related to Capistrano and/or your configuration.

Have you added `.rbenv-vars` to the `:linked_files` variable in `deploy.rb`, like the [Usage section mentions](https://github.com/runar/capistrano-linked-files#usage)?

Also, the relevant Capistrano task may be found [here](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/tasks/deploy.rake#L131).

**Comment by zhisme** [comment]
@runar yes, that's my mistake. I didn't read  about linked files well. So thank you for pointing me out.
